# Generated by Django 5.0.6 on 2024-06-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aul_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='post_cover',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='image',
            field=models.ImageField(default='default/default.jpg', upload_to='images/'),
        ),
    ]
