# Generated by Django 5.0.6 on 2024-06-16 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aul_blog', '0002_remove_blog_post_post_cover_blog_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
